server:
  port: 8082

spring:
    datasource:
        name: test
        #财政厅数据库
#          url: jdbc:mysql://10.108.6.121:3306/czt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#          username: root
#          password: 123
        #网络中心数据库
        url: jdbc:mysql://git.ncu.edu.cn:3306/czt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: cztadmin
        password: czt123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql